// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: whitelist/query.proto

package types

import (
	context "context"
	fmt "fmt"
	query "github.com/cosmos/cosmos-sdk/types/query"
	_ "github.com/gogo/protobuf/gogoproto"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	// params holds all the parameters of this module.
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryGetBuyerIdsRequest struct {
	AccAddr string `protobuf:"bytes,1,opt,name=accAddr,proto3" json:"accAddr,omitempty"`
}

func (m *QueryGetBuyerIdsRequest) Reset()         { *m = QueryGetBuyerIdsRequest{} }
func (m *QueryGetBuyerIdsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuyerIdsRequest) ProtoMessage()    {}
func (*QueryGetBuyerIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{2}
}
func (m *QueryGetBuyerIdsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuyerIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuyerIdsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuyerIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuyerIdsRequest.Merge(m, src)
}
func (m *QueryGetBuyerIdsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuyerIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuyerIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuyerIdsRequest proto.InternalMessageInfo

func (m *QueryGetBuyerIdsRequest) GetAccAddr() string {
	if m != nil {
		return m.AccAddr
	}
	return ""
}

type QueryGetBuyerIdsResponse struct {
	BuyerIds BuyerIds `protobuf:"bytes,1,opt,name=buyerIds,proto3" json:"buyerIds"`
}

func (m *QueryGetBuyerIdsResponse) Reset()         { *m = QueryGetBuyerIdsResponse{} }
func (m *QueryGetBuyerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuyerIdsResponse) ProtoMessage()    {}
func (*QueryGetBuyerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{3}
}
func (m *QueryGetBuyerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuyerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuyerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuyerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuyerIdsResponse.Merge(m, src)
}
func (m *QueryGetBuyerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuyerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuyerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuyerIdsResponse proto.InternalMessageInfo

func (m *QueryGetBuyerIdsResponse) GetBuyerIds() BuyerIds {
	if m != nil {
		return m.BuyerIds
	}
	return BuyerIds{}
}

type QueryAllBuyerIdsRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuyerIdsRequest) Reset()         { *m = QueryAllBuyerIdsRequest{} }
func (m *QueryAllBuyerIdsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuyerIdsRequest) ProtoMessage()    {}
func (*QueryAllBuyerIdsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{4}
}
func (m *QueryAllBuyerIdsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuyerIdsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuyerIdsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuyerIdsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuyerIdsRequest.Merge(m, src)
}
func (m *QueryAllBuyerIdsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuyerIdsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuyerIdsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuyerIdsRequest proto.InternalMessageInfo

func (m *QueryAllBuyerIdsRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBuyerIdsResponse struct {
	BuyerIds   []BuyerIds          `protobuf:"bytes,1,rep,name=buyerIds,proto3" json:"buyerIds"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuyerIdsResponse) Reset()         { *m = QueryAllBuyerIdsResponse{} }
func (m *QueryAllBuyerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuyerIdsResponse) ProtoMessage()    {}
func (*QueryAllBuyerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{5}
}
func (m *QueryAllBuyerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuyerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuyerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuyerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuyerIdsResponse.Merge(m, src)
}
func (m *QueryAllBuyerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuyerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuyerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuyerIdsResponse proto.InternalMessageInfo

func (m *QueryAllBuyerIdsResponse) GetBuyerIds() []BuyerIds {
	if m != nil {
		return m.BuyerIds
	}
	return nil
}

func (m *QueryAllBuyerIdsResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryGetBuyersRequest struct {
	BuyerId string `protobuf:"bytes,1,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *QueryGetBuyersRequest) Reset()         { *m = QueryGetBuyersRequest{} }
func (m *QueryGetBuyersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuyersRequest) ProtoMessage()    {}
func (*QueryGetBuyersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{6}
}
func (m *QueryGetBuyersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuyersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuyersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuyersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuyersRequest.Merge(m, src)
}
func (m *QueryGetBuyersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuyersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuyersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuyersRequest proto.InternalMessageInfo

func (m *QueryGetBuyersRequest) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

type QueryGetBuyersResponse struct {
	Buyers Buyers `protobuf:"bytes,1,opt,name=buyers,proto3" json:"buyers"`
}

func (m *QueryGetBuyersResponse) Reset()         { *m = QueryGetBuyersResponse{} }
func (m *QueryGetBuyersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryGetBuyersResponse) ProtoMessage()    {}
func (*QueryGetBuyersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{7}
}
func (m *QueryGetBuyersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryGetBuyersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryGetBuyersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryGetBuyersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryGetBuyersResponse.Merge(m, src)
}
func (m *QueryGetBuyersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryGetBuyersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryGetBuyersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryGetBuyersResponse proto.InternalMessageInfo

func (m *QueryGetBuyersResponse) GetBuyers() Buyers {
	if m != nil {
		return m.Buyers
	}
	return Buyers{}
}

type QueryAllBuyersRequest struct {
	Pagination *query.PageRequest `protobuf:"bytes,1,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuyersRequest) Reset()         { *m = QueryAllBuyersRequest{} }
func (m *QueryAllBuyersRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuyersRequest) ProtoMessage()    {}
func (*QueryAllBuyersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{8}
}
func (m *QueryAllBuyersRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuyersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuyersRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuyersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuyersRequest.Merge(m, src)
}
func (m *QueryAllBuyersRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuyersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuyersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuyersRequest proto.InternalMessageInfo

func (m *QueryAllBuyersRequest) GetPagination() *query.PageRequest {
	if m != nil {
		return m.Pagination
	}
	return nil
}

type QueryAllBuyersResponse struct {
	Buyers     []Buyers            `protobuf:"bytes,1,rep,name=buyers,proto3" json:"buyers"`
	Pagination *query.PageResponse `protobuf:"bytes,2,opt,name=pagination,proto3" json:"pagination,omitempty"`
}

func (m *QueryAllBuyersResponse) Reset()         { *m = QueryAllBuyersResponse{} }
func (m *QueryAllBuyersResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAllBuyersResponse) ProtoMessage()    {}
func (*QueryAllBuyersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8ae4e6c2632e3347, []int{9}
}
func (m *QueryAllBuyersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAllBuyersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAllBuyersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAllBuyersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAllBuyersResponse.Merge(m, src)
}
func (m *QueryAllBuyersResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAllBuyersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAllBuyersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAllBuyersResponse proto.InternalMessageInfo

func (m *QueryAllBuyersResponse) GetBuyers() []Buyers {
	if m != nil {
		return m.Buyers
	}
	return nil
}

func (m *QueryAllBuyersResponse) GetPagination() *query.PageResponse {
	if m != nil {
		return m.Pagination
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "crowlabs.gamma.whitelist.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "crowlabs.gamma.whitelist.QueryParamsResponse")
	proto.RegisterType((*QueryGetBuyerIdsRequest)(nil), "crowlabs.gamma.whitelist.QueryGetBuyerIdsRequest")
	proto.RegisterType((*QueryGetBuyerIdsResponse)(nil), "crowlabs.gamma.whitelist.QueryGetBuyerIdsResponse")
	proto.RegisterType((*QueryAllBuyerIdsRequest)(nil), "crowlabs.gamma.whitelist.QueryAllBuyerIdsRequest")
	proto.RegisterType((*QueryAllBuyerIdsResponse)(nil), "crowlabs.gamma.whitelist.QueryAllBuyerIdsResponse")
	proto.RegisterType((*QueryGetBuyersRequest)(nil), "crowlabs.gamma.whitelist.QueryGetBuyersRequest")
	proto.RegisterType((*QueryGetBuyersResponse)(nil), "crowlabs.gamma.whitelist.QueryGetBuyersResponse")
	proto.RegisterType((*QueryAllBuyersRequest)(nil), "crowlabs.gamma.whitelist.QueryAllBuyersRequest")
	proto.RegisterType((*QueryAllBuyersResponse)(nil), "crowlabs.gamma.whitelist.QueryAllBuyersResponse")
}

func init() { proto.RegisterFile("whitelist/query.proto", fileDescriptor_8ae4e6c2632e3347) }

var fileDescriptor_8ae4e6c2632e3347 = []byte{
	// 626 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x95, 0x4d, 0x6f, 0xd3, 0x30,
	0x18, 0xc7, 0xeb, 0x0d, 0xca, 0xe6, 0xdd, 0xcc, 0x36, 0x4a, 0x85, 0xc2, 0x30, 0x68, 0xbc, 0xad,
	0xf6, 0xda, 0x4a, 0x1c, 0x91, 0x5a, 0xa1, 0x4d, 0xdc, 0x46, 0x25, 0x24, 0xc4, 0x65, 0x38, 0xad,
	0x95, 0x45, 0x4a, 0xeb, 0x2c, 0x4e, 0x19, 0xd5, 0xb4, 0x0b, 0x9f, 0x60, 0x12, 0x27, 0x6e, 0xc0,
	0x6d, 0x7c, 0x92, 0x1d, 0x27, 0x71, 0xe1, 0x84, 0x50, 0xcb, 0x07, 0x41, 0xb1, 0x9d, 0xbe, 0xa5,
	0x25, 0x19, 0xda, 0xad, 0x79, 0xfc, 0xfc, 0x9f, 0xe7, 0xe7, 0xe7, 0xc5, 0x85, 0x6b, 0x47, 0x07,
	0x6e, 0xc8, 0x3d, 0x57, 0x86, 0xf4, 0xb0, 0xcb, 0x83, 0x1e, 0xf1, 0x03, 0x11, 0x0a, 0x54, 0x68,
	0x06, 0xe2, 0xc8, 0x63, 0xb6, 0x24, 0x0e, 0x6b, 0xb7, 0x19, 0x19, 0x7a, 0x15, 0x57, 0x1d, 0xe1,
	0x08, 0xe5, 0x44, 0xa3, 0x5f, 0xda, 0xbf, 0x78, 0xc7, 0x11, 0xc2, 0xf1, 0x38, 0x65, 0xbe, 0x4b,
	0x59, 0xa7, 0x23, 0x42, 0x16, 0xba, 0xa2, 0x23, 0xcd, 0xe9, 0x93, 0xa6, 0x90, 0x6d, 0x21, 0xa9,
	0xcd, 0x24, 0xd7, 0x69, 0xe8, 0xfb, 0xb2, 0xcd, 0x43, 0x56, 0xa6, 0x3e, 0x73, 0xdc, 0x8e, 0x72,
	0x36, 0xbe, 0xeb, 0x23, 0x20, 0x9f, 0x05, 0xac, 0x1d, 0xc7, 0xb8, 0x3d, 0xb2, 0xdb, 0xdd, 0x1e,
	0x0f, 0xf6, 0xdd, 0x96, 0x4c, 0x4a, 0xd4, 0x51, 0x6c, 0x5f, 0x9b, 0xb2, 0x6b, 0x33, 0x5e, 0x85,
	0xe8, 0x55, 0xc4, 0xb0, 0xa7, 0xc2, 0x37, 0xf8, 0x61, 0x97, 0xcb, 0x10, 0xbf, 0x86, 0x37, 0x27,
	0xac, 0xd2, 0x17, 0x1d, 0xc9, 0xd1, 0x73, 0x98, 0xd7, 0x18, 0x05, 0xb0, 0x01, 0x1e, 0xad, 0x54,
	0x36, 0xc8, 0xbc, 0xca, 0x10, 0xad, 0xac, 0x5f, 0x3b, 0xff, 0x75, 0x37, 0xd7, 0x30, 0x2a, 0x5c,
	0x85, 0xb7, 0x54, 0xd8, 0x5d, 0x1e, 0xd6, 0x23, 0x86, 0x97, 0xad, 0x38, 0x23, 0x2a, 0xc0, 0x1b,
	0xac, 0xd9, 0xac, 0xb5, 0x5a, 0x81, 0x8a, 0xbd, 0xdc, 0x88, 0x3f, 0xf1, 0x3b, 0x58, 0x48, 0x8a,
	0x0c, 0xd0, 0x0b, 0xb8, 0x64, 0x1b, 0x9b, 0x41, 0xc2, 0xf3, 0x91, 0x62, 0xb5, 0x81, 0x1a, 0x2a,
	0x31, 0x33, 0x58, 0x35, 0xcf, 0x9b, 0xc6, 0xda, 0x81, 0x70, 0xd4, 0x14, 0x93, 0x62, 0x93, 0xe8,
	0x0e, 0x92, 0xa8, 0x83, 0x44, 0x0f, 0x8a, 0xe9, 0x20, 0xd9, 0x63, 0x0e, 0x37, 0xda, 0xc6, 0x98,
	0x12, 0x9f, 0x01, 0x73, 0x8b, 0x89, 0x1c, 0x33, 0x6f, 0xb1, 0xf8, 0x7f, 0xb7, 0x40, 0xbb, 0x13,
	0xa8, 0x0b, 0x0a, 0xf5, 0x61, 0x2a, 0xaa, 0x46, 0x98, 0x60, 0x2d, 0xc3, 0xb5, 0x89, 0x82, 0x8f,
	0xf7, 0xc8, 0x64, 0x8b, 0x7b, 0x64, 0x3e, 0xf1, 0x1b, 0xb8, 0x3e, 0x2d, 0x19, 0x8d, 0x8c, 0x1e,
	0xc3, 0xf4, 0x91, 0xd1, 0xca, 0x78, 0x64, 0xb4, 0x0a, 0xef, 0x1b, 0x98, 0xb8, 0x6e, 0x57, 0xde,
	0x99, 0xaf, 0xc0, 0xb0, 0x8f, 0x65, 0x98, 0xc1, 0xbe, 0x78, 0x79, 0xf6, 0x2b, 0xeb, 0x48, 0xe5,
	0x7b, 0x1e, 0x5e, 0x57, 0x8c, 0xe8, 0x14, 0xc0, 0xbc, 0x5e, 0x2d, 0xb4, 0x35, 0x9f, 0x26, 0xb9,
	0xd1, 0xc5, 0x52, 0x46, 0x6f, 0x9d, 0x1d, 0x3f, 0xfe, 0xf8, 0xe3, 0xcf, 0xa7, 0x85, 0xfb, 0xe8,
	0x1e, 0x8d, 0x64, 0xa5, 0x48, 0x47, 0x95, 0x8e, 0x4e, 0xbf, 0x48, 0xe8, 0x0c, 0xc0, 0xa5, 0x78,
	0x28, 0x51, 0x39, 0x25, 0x4d, 0x72, 0xf3, 0x8b, 0x95, 0xcb, 0x48, 0x0c, 0xde, 0x33, 0x85, 0xb7,
	0x8d, 0xc8, 0x3f, 0xf0, 0x86, 0x0f, 0x23, 0x3d, 0x36, 0x4f, 0xc9, 0x09, 0xfa, 0x06, 0xe0, 0x4a,
	0x1c, 0xac, 0xe6, 0x79, 0xa9, 0xb8, 0xc9, 0x17, 0x21, 0x15, 0x77, 0xc6, 0x82, 0xe3, 0x2d, 0x85,
	0xbb, 0x89, 0x1e, 0x64, 0xc1, 0x45, 0x5f, 0x00, 0xcc, 0xeb, 0x79, 0x42, 0x34, 0x63, 0x6d, 0x86,
	0x74, 0xdb, 0xd9, 0x05, 0x86, 0xad, 0xaa, 0xd8, 0x4a, 0xe8, 0x69, 0x1a, 0x9b, 0xa4, 0xc7, 0x66,
	0xdd, 0x4f, 0xd0, 0x67, 0x00, 0x97, 0x75, 0x9c, 0xa8, 0x8a, 0x34, 0x63, 0x49, 0x32, 0x53, 0x26,
	0x56, 0x31, 0xd3, 0x3c, 0x6a, 0xca, 0xfa, 0xce, 0x79, 0xdf, 0x02, 0x17, 0x7d, 0x0b, 0xfc, 0xee,
	0x5b, 0xe0, 0x74, 0x60, 0xe5, 0x2e, 0x06, 0x56, 0xee, 0xe7, 0xc0, 0xca, 0xbd, 0xdd, 0x72, 0xdc,
	0xf0, 0xa0, 0x6b, 0x93, 0xa6, 0x68, 0x27, 0xc2, 0x7c, 0x18, 0x0b, 0x14, 0xf6, 0x7c, 0x2e, 0xed,
	0xbc, 0xfa, 0x83, 0xac, 0xfe, 0x0d, 0x00, 0x00, 0xff, 0xff, 0x07, 0x22, 0xe7, 0xd9, 0x15, 0x08,
	0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// Queries a BuyerIds by index.
	BuyerIds(ctx context.Context, in *QueryGetBuyerIdsRequest, opts ...grpc.CallOption) (*QueryGetBuyerIdsResponse, error)
	// Queries a list of BuyerIds items.
	BuyerIdsAll(ctx context.Context, in *QueryAllBuyerIdsRequest, opts ...grpc.CallOption) (*QueryAllBuyerIdsResponse, error)
	// Queries a Buyers by index.
	Buyers(ctx context.Context, in *QueryGetBuyersRequest, opts ...grpc.CallOption) (*QueryGetBuyersResponse, error)
	// Queries a list of Buyers items.
	BuyersAll(ctx context.Context, in *QueryAllBuyersRequest, opts ...grpc.CallOption) (*QueryAllBuyersResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuyerIds(ctx context.Context, in *QueryGetBuyerIdsRequest, opts ...grpc.CallOption) (*QueryGetBuyerIdsResponse, error) {
	out := new(QueryGetBuyerIdsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Query/BuyerIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuyerIdsAll(ctx context.Context, in *QueryAllBuyerIdsRequest, opts ...grpc.CallOption) (*QueryAllBuyerIdsResponse, error) {
	out := new(QueryAllBuyerIdsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Query/BuyerIdsAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) Buyers(ctx context.Context, in *QueryGetBuyersRequest, opts ...grpc.CallOption) (*QueryGetBuyersResponse, error) {
	out := new(QueryGetBuyersResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Query/Buyers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) BuyersAll(ctx context.Context, in *QueryAllBuyersRequest, opts ...grpc.CallOption) (*QueryAllBuyersResponse, error) {
	out := new(QueryAllBuyersResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Query/BuyersAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// Queries a BuyerIds by index.
	BuyerIds(context.Context, *QueryGetBuyerIdsRequest) (*QueryGetBuyerIdsResponse, error)
	// Queries a list of BuyerIds items.
	BuyerIdsAll(context.Context, *QueryAllBuyerIdsRequest) (*QueryAllBuyerIdsResponse, error)
	// Queries a Buyers by index.
	Buyers(context.Context, *QueryGetBuyersRequest) (*QueryGetBuyersResponse, error)
	// Queries a list of Buyers items.
	BuyersAll(context.Context, *QueryAllBuyersRequest) (*QueryAllBuyersResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) BuyerIds(ctx context.Context, req *QueryGetBuyerIdsRequest) (*QueryGetBuyerIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyerIds not implemented")
}
func (*UnimplementedQueryServer) BuyerIdsAll(ctx context.Context, req *QueryAllBuyerIdsRequest) (*QueryAllBuyerIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyerIdsAll not implemented")
}
func (*UnimplementedQueryServer) Buyers(ctx context.Context, req *QueryGetBuyersRequest) (*QueryGetBuyersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Buyers not implemented")
}
func (*UnimplementedQueryServer) BuyersAll(ctx context.Context, req *QueryAllBuyersRequest) (*QueryAllBuyersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BuyersAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuyerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBuyerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuyerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Query/BuyerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuyerIds(ctx, req.(*QueryGetBuyerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuyerIdsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBuyerIdsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuyerIdsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Query/BuyerIdsAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuyerIdsAll(ctx, req.(*QueryAllBuyerIdsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_Buyers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryGetBuyersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Buyers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Query/Buyers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Buyers(ctx, req.(*QueryGetBuyersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_BuyersAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAllBuyersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).BuyersAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Query/BuyersAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).BuyersAll(ctx, req.(*QueryAllBuyersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crowlabs.gamma.whitelist.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "BuyerIds",
			Handler:    _Query_BuyerIds_Handler,
		},
		{
			MethodName: "BuyerIdsAll",
			Handler:    _Query_BuyerIdsAll_Handler,
		},
		{
			MethodName: "Buyers",
			Handler:    _Query_Buyers_Handler,
		},
		{
			MethodName: "BuyersAll",
			Handler:    _Query_BuyersAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitelist/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryGetBuyerIdsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuyerIdsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuyerIdsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccAddr) > 0 {
		i -= len(m.AccAddr)
		copy(dAtA[i:], m.AccAddr)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.AccAddr)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBuyerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuyerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuyerIdsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.BuyerIds.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBuyerIdsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuyerIdsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuyerIdsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBuyerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuyerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuyerIdsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.BuyerIds) > 0 {
		for iNdEx := len(m.BuyerIds) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.BuyerIds[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBuyersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuyersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuyersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryGetBuyersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryGetBuyersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryGetBuyersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Buyers.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAllBuyersRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuyersRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuyersRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryAllBuyersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAllBuyersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAllBuyersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Pagination != nil {
		{
			size, err := m.Pagination.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintQuery(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x12
	}
	if len(m.Buyers) > 0 {
		for iNdEx := len(m.Buyers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Buyers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryGetBuyerIdsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.AccAddr)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBuyerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BuyerIds.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBuyerIdsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBuyerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.BuyerIds) > 0 {
		for _, e := range m.BuyerIds {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBuyersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryGetBuyersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Buyers.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAllBuyersRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryAllBuyersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Buyers) > 0 {
		for _, e := range m.Buyers {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	if m.Pagination != nil {
		l = m.Pagination.Size()
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuyerIdsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuyerIdsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuyerIdsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuyerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuyerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuyerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BuyerIds.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuyerIdsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuyerIdsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuyerIdsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuyerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuyerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuyerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerIds", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerIds = append(m.BuyerIds, BuyerIds{})
			if err := m.BuyerIds[len(m.BuyerIds)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuyersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuyersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuyersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryGetBuyersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryGetBuyersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryGetBuyersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Buyers.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuyersRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuyersRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuyersRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageRequest{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAllBuyersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAllBuyersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAllBuyersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Buyers = append(m.Buyers, Buyers{})
			if err := m.Buyers[len(m.Buyers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pagination", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Pagination == nil {
				m.Pagination = &query.PageResponse{}
			}
			if err := m.Pagination.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
