// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: whitelist/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	grpc1 "github.com/gogo/protobuf/grpc"
	proto "github.com/gogo/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgCreateBuyerIds struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AccAddr string `protobuf:"bytes,2,opt,name=accAddr,proto3" json:"accAddr,omitempty"`
	BuyerId string `protobuf:"bytes,3,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *MsgCreateBuyerIds) Reset()         { *m = MsgCreateBuyerIds{} }
func (m *MsgCreateBuyerIds) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBuyerIds) ProtoMessage()    {}
func (*MsgCreateBuyerIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{0}
}
func (m *MsgCreateBuyerIds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBuyerIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBuyerIds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBuyerIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBuyerIds.Merge(m, src)
}
func (m *MsgCreateBuyerIds) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBuyerIds) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBuyerIds.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBuyerIds proto.InternalMessageInfo

func (m *MsgCreateBuyerIds) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateBuyerIds) GetAccAddr() string {
	if m != nil {
		return m.AccAddr
	}
	return ""
}

func (m *MsgCreateBuyerIds) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

type MsgCreateBuyerIdsResponse struct {
}

func (m *MsgCreateBuyerIdsResponse) Reset()         { *m = MsgCreateBuyerIdsResponse{} }
func (m *MsgCreateBuyerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBuyerIdsResponse) ProtoMessage()    {}
func (*MsgCreateBuyerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{1}
}
func (m *MsgCreateBuyerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBuyerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBuyerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBuyerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBuyerIdsResponse.Merge(m, src)
}
func (m *MsgCreateBuyerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBuyerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBuyerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBuyerIdsResponse proto.InternalMessageInfo

type MsgUpdateBuyerIds struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AccAddr string `protobuf:"bytes,2,opt,name=accAddr,proto3" json:"accAddr,omitempty"`
	BuyerId string `protobuf:"bytes,3,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *MsgUpdateBuyerIds) Reset()         { *m = MsgUpdateBuyerIds{} }
func (m *MsgUpdateBuyerIds) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBuyerIds) ProtoMessage()    {}
func (*MsgUpdateBuyerIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{2}
}
func (m *MsgUpdateBuyerIds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBuyerIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBuyerIds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBuyerIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBuyerIds.Merge(m, src)
}
func (m *MsgUpdateBuyerIds) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBuyerIds) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBuyerIds.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBuyerIds proto.InternalMessageInfo

func (m *MsgUpdateBuyerIds) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateBuyerIds) GetAccAddr() string {
	if m != nil {
		return m.AccAddr
	}
	return ""
}

func (m *MsgUpdateBuyerIds) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

type MsgUpdateBuyerIdsResponse struct {
}

func (m *MsgUpdateBuyerIdsResponse) Reset()         { *m = MsgUpdateBuyerIdsResponse{} }
func (m *MsgUpdateBuyerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBuyerIdsResponse) ProtoMessage()    {}
func (*MsgUpdateBuyerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{3}
}
func (m *MsgUpdateBuyerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBuyerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBuyerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBuyerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBuyerIdsResponse.Merge(m, src)
}
func (m *MsgUpdateBuyerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBuyerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBuyerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBuyerIdsResponse proto.InternalMessageInfo

type MsgDeleteBuyerIds struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	AccAddr string `protobuf:"bytes,2,opt,name=accAddr,proto3" json:"accAddr,omitempty"`
}

func (m *MsgDeleteBuyerIds) Reset()         { *m = MsgDeleteBuyerIds{} }
func (m *MsgDeleteBuyerIds) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBuyerIds) ProtoMessage()    {}
func (*MsgDeleteBuyerIds) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{4}
}
func (m *MsgDeleteBuyerIds) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBuyerIds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBuyerIds.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBuyerIds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBuyerIds.Merge(m, src)
}
func (m *MsgDeleteBuyerIds) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBuyerIds) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBuyerIds.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBuyerIds proto.InternalMessageInfo

func (m *MsgDeleteBuyerIds) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteBuyerIds) GetAccAddr() string {
	if m != nil {
		return m.AccAddr
	}
	return ""
}

type MsgDeleteBuyerIdsResponse struct {
}

func (m *MsgDeleteBuyerIdsResponse) Reset()         { *m = MsgDeleteBuyerIdsResponse{} }
func (m *MsgDeleteBuyerIdsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBuyerIdsResponse) ProtoMessage()    {}
func (*MsgDeleteBuyerIdsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{5}
}
func (m *MsgDeleteBuyerIdsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBuyerIdsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBuyerIdsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBuyerIdsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBuyerIdsResponse.Merge(m, src)
}
func (m *MsgDeleteBuyerIdsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBuyerIdsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBuyerIdsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBuyerIdsResponse proto.InternalMessageInfo

type MsgCreateBuyers struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	BuyerId string `protobuf:"bytes,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	Buyer   *Buyer `protobuf:"bytes,3,opt,name=buyer,proto3" json:"buyer,omitempty"`
}

func (m *MsgCreateBuyers) Reset()         { *m = MsgCreateBuyers{} }
func (m *MsgCreateBuyers) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBuyers) ProtoMessage()    {}
func (*MsgCreateBuyers) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{6}
}
func (m *MsgCreateBuyers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBuyers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBuyers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBuyers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBuyers.Merge(m, src)
}
func (m *MsgCreateBuyers) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBuyers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBuyers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBuyers proto.InternalMessageInfo

func (m *MsgCreateBuyers) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgCreateBuyers) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *MsgCreateBuyers) GetBuyer() *Buyer {
	if m != nil {
		return m.Buyer
	}
	return nil
}

type MsgCreateBuyersResponse struct {
}

func (m *MsgCreateBuyersResponse) Reset()         { *m = MsgCreateBuyersResponse{} }
func (m *MsgCreateBuyersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgCreateBuyersResponse) ProtoMessage()    {}
func (*MsgCreateBuyersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{7}
}
func (m *MsgCreateBuyersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgCreateBuyersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgCreateBuyersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgCreateBuyersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgCreateBuyersResponse.Merge(m, src)
}
func (m *MsgCreateBuyersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgCreateBuyersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgCreateBuyersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgCreateBuyersResponse proto.InternalMessageInfo

type MsgUpdateBuyers struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	BuyerId string `protobuf:"bytes,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
	Buyer   *Buyer `protobuf:"bytes,3,opt,name=buyer,proto3" json:"buyer,omitempty"`
}

func (m *MsgUpdateBuyers) Reset()         { *m = MsgUpdateBuyers{} }
func (m *MsgUpdateBuyers) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBuyers) ProtoMessage()    {}
func (*MsgUpdateBuyers) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{8}
}
func (m *MsgUpdateBuyers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBuyers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBuyers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBuyers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBuyers.Merge(m, src)
}
func (m *MsgUpdateBuyers) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBuyers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBuyers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBuyers proto.InternalMessageInfo

func (m *MsgUpdateBuyers) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgUpdateBuyers) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

func (m *MsgUpdateBuyers) GetBuyer() *Buyer {
	if m != nil {
		return m.Buyer
	}
	return nil
}

type MsgUpdateBuyersResponse struct {
}

func (m *MsgUpdateBuyersResponse) Reset()         { *m = MsgUpdateBuyersResponse{} }
func (m *MsgUpdateBuyersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateBuyersResponse) ProtoMessage()    {}
func (*MsgUpdateBuyersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{9}
}
func (m *MsgUpdateBuyersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateBuyersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateBuyersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateBuyersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateBuyersResponse.Merge(m, src)
}
func (m *MsgUpdateBuyersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateBuyersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateBuyersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateBuyersResponse proto.InternalMessageInfo

type MsgDeleteBuyers struct {
	Creator string `protobuf:"bytes,1,opt,name=creator,proto3" json:"creator,omitempty"`
	BuyerId string `protobuf:"bytes,2,opt,name=buyerId,proto3" json:"buyerId,omitempty"`
}

func (m *MsgDeleteBuyers) Reset()         { *m = MsgDeleteBuyers{} }
func (m *MsgDeleteBuyers) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBuyers) ProtoMessage()    {}
func (*MsgDeleteBuyers) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{10}
}
func (m *MsgDeleteBuyers) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBuyers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBuyers.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBuyers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBuyers.Merge(m, src)
}
func (m *MsgDeleteBuyers) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBuyers) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBuyers.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBuyers proto.InternalMessageInfo

func (m *MsgDeleteBuyers) GetCreator() string {
	if m != nil {
		return m.Creator
	}
	return ""
}

func (m *MsgDeleteBuyers) GetBuyerId() string {
	if m != nil {
		return m.BuyerId
	}
	return ""
}

type MsgDeleteBuyersResponse struct {
}

func (m *MsgDeleteBuyersResponse) Reset()         { *m = MsgDeleteBuyersResponse{} }
func (m *MsgDeleteBuyersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgDeleteBuyersResponse) ProtoMessage()    {}
func (*MsgDeleteBuyersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3bd336a39a8c9db2, []int{11}
}
func (m *MsgDeleteBuyersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgDeleteBuyersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgDeleteBuyersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgDeleteBuyersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgDeleteBuyersResponse.Merge(m, src)
}
func (m *MsgDeleteBuyersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgDeleteBuyersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgDeleteBuyersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgDeleteBuyersResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgCreateBuyerIds)(nil), "crowlabs.gamma.whitelist.MsgCreateBuyerIds")
	proto.RegisterType((*MsgCreateBuyerIdsResponse)(nil), "crowlabs.gamma.whitelist.MsgCreateBuyerIdsResponse")
	proto.RegisterType((*MsgUpdateBuyerIds)(nil), "crowlabs.gamma.whitelist.MsgUpdateBuyerIds")
	proto.RegisterType((*MsgUpdateBuyerIdsResponse)(nil), "crowlabs.gamma.whitelist.MsgUpdateBuyerIdsResponse")
	proto.RegisterType((*MsgDeleteBuyerIds)(nil), "crowlabs.gamma.whitelist.MsgDeleteBuyerIds")
	proto.RegisterType((*MsgDeleteBuyerIdsResponse)(nil), "crowlabs.gamma.whitelist.MsgDeleteBuyerIdsResponse")
	proto.RegisterType((*MsgCreateBuyers)(nil), "crowlabs.gamma.whitelist.MsgCreateBuyers")
	proto.RegisterType((*MsgCreateBuyersResponse)(nil), "crowlabs.gamma.whitelist.MsgCreateBuyersResponse")
	proto.RegisterType((*MsgUpdateBuyers)(nil), "crowlabs.gamma.whitelist.MsgUpdateBuyers")
	proto.RegisterType((*MsgUpdateBuyersResponse)(nil), "crowlabs.gamma.whitelist.MsgUpdateBuyersResponse")
	proto.RegisterType((*MsgDeleteBuyers)(nil), "crowlabs.gamma.whitelist.MsgDeleteBuyers")
	proto.RegisterType((*MsgDeleteBuyersResponse)(nil), "crowlabs.gamma.whitelist.MsgDeleteBuyersResponse")
}

func init() { proto.RegisterFile("whitelist/tx.proto", fileDescriptor_3bd336a39a8c9db2) }

var fileDescriptor_3bd336a39a8c9db2 = []byte{
	// 422 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x95, 0xcb, 0x4a, 0xc3, 0x40,
	0x14, 0x86, 0x9b, 0x96, 0x2a, 0x8e, 0xa2, 0x18, 0x50, 0xd3, 0x08, 0x51, 0xba, 0xb2, 0xa8, 0x09,
	0xb6, 0xf8, 0x00, 0xd6, 0x1b, 0x2e, 0xba, 0x29, 0xb8, 0x71, 0x23, 0xb9, 0x0c, 0x69, 0x20, 0x35,
	0x61, 0x26, 0xa5, 0x2d, 0xf8, 0x10, 0xbe, 0x87, 0x2f, 0xe2, 0xb2, 0x4b, 0x97, 0xd2, 0xbe, 0x88,
	0xcc, 0xe4, 0x62, 0x66, 0x9a, 0x36, 0x51, 0x11, 0x77, 0x9d, 0x73, 0xfe, 0x39, 0xdf, 0x99, 0x9f,
	0x9f, 0x06, 0x88, 0xc3, 0x9e, 0x13, 0x40, 0xd7, 0xc1, 0x81, 0x16, 0x8c, 0x54, 0x1f, 0x79, 0x81,
	0x27, 0x4a, 0x26, 0xf2, 0x86, 0xae, 0x6e, 0x60, 0xd5, 0xd6, 0xfb, 0x7d, 0x5d, 0x4d, 0x24, 0x72,
	0xed, 0x4b, 0x6d, 0x0c, 0xc6, 0x10, 0x3d, 0x3a, 0x16, 0x0e, 0x2f, 0xc9, 0xbb, 0x5c, 0x2b, 0xae,
	0xef, 0x70, 0xf5, 0xb0, 0x5c, 0xd7, 0xc1, 0x76, 0x07, 0xdb, 0x97, 0x08, 0xea, 0x01, 0x6c, 0x93,
	0xfa, 0x9d, 0x85, 0x45, 0x09, 0xac, 0x9a, 0xa4, 0xe2, 0x21, 0x49, 0x38, 0x14, 0x8e, 0xd6, 0xba,
	0xf1, 0x91, 0x74, 0x74, 0xd3, 0xbc, 0xb0, 0x2c, 0x24, 0x95, 0xc3, 0x4e, 0x74, 0x24, 0x1d, 0x23,
	0xbc, 0x2f, 0x55, 0xc2, 0x4e, 0x74, 0xac, 0xef, 0x83, 0xda, 0x1c, 0xa2, 0x0b, 0xb1, 0xef, 0x3d,
	0x61, 0x18, 0xf1, 0xef, 0x7d, 0xeb, 0xaf, 0xf9, 0x2c, 0x22, 0xe1, 0xdf, 0x52, 0xfe, 0x15, 0x74,
	0xe1, 0xef, 0xf8, 0x11, 0x85, 0x1d, 0x94, 0x50, 0x9e, 0xc1, 0x16, 0x6b, 0x41, 0x0e, 0x23, 0x7e,
	0x49, 0x99, 0x79, 0x89, 0x78, 0x0e, 0xaa, 0xf4, 0x27, 0x7d, 0xe1, 0x7a, 0xf3, 0x40, 0x5d, 0x14,
	0x10, 0x95, 0x42, 0xba, 0xa1, 0xba, 0x5e, 0x03, 0x7b, 0x1c, 0x9d, 0x5b, 0x2c, 0xe5, 0xcd, 0x3f,
	0x2c, 0x96, 0xa6, 0x27, 0x8b, 0x5d, 0xd3, 0xc5, 0x52, 0x76, 0xfe, 0x68, 0xb1, 0x88, 0x90, 0x1e,
	0x13, 0x13, 0x9a, 0xaf, 0x55, 0x50, 0xe9, 0x60, 0x5b, 0x44, 0x60, 0x93, 0x8b, 0xff, 0xf1, 0xe2,
	0xf5, 0xe7, 0x82, 0x2c, 0xb7, 0xbe, 0x21, 0x8e, 0xd9, 0x84, 0xc9, 0x45, 0x7e, 0x39, 0x93, 0x15,
	0xe7, 0x30, 0xb3, 0x93, 0x4e, 0x98, 0x5c, 0xcc, 0x97, 0x33, 0x59, 0x71, 0x0e, 0x33, 0x3b, 0xf7,
	0xa2, 0x0b, 0x36, 0x98, 0xd0, 0x37, 0x8a, 0x9a, 0x85, 0xe5, 0xb3, 0xc2, 0xd2, 0x34, 0x8d, 0x49,
	0x72, 0xa3, 0xa8, 0x4d, 0x79, 0xb4, 0xac, 0x84, 0x12, 0x1a, 0x13, 0xcf, 0x46, 0x51, 0x83, 0xf2,
	0x68, 0x59, 0x69, 0x6d, 0xdf, 0xbc, 0x4d, 0x15, 0x61, 0x32, 0x55, 0x84, 0x8f, 0xa9, 0x22, 0xbc,
	0xcc, 0x94, 0xd2, 0x64, 0xa6, 0x94, 0xde, 0x67, 0x4a, 0xe9, 0xe1, 0xc4, 0x76, 0x82, 0xde, 0xc0,
	0x50, 0x4d, 0xaf, 0xaf, 0x91, 0xb1, 0xa7, 0x64, 0xae, 0x46, 0xe7, 0x6a, 0x23, 0x2d, 0xf5, 0x59,
	0x19, 0xfb, 0x10, 0x1b, 0x2b, 0xf4, 0x6f, 0xbf, 0xf5, 0x19, 0x00, 0x00, 0xff, 0xff, 0x4d, 0xd1,
	0x56, 0x6d, 0x70, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	CreateBuyerIds(ctx context.Context, in *MsgCreateBuyerIds, opts ...grpc.CallOption) (*MsgCreateBuyerIdsResponse, error)
	UpdateBuyerIds(ctx context.Context, in *MsgUpdateBuyerIds, opts ...grpc.CallOption) (*MsgUpdateBuyerIdsResponse, error)
	DeleteBuyerIds(ctx context.Context, in *MsgDeleteBuyerIds, opts ...grpc.CallOption) (*MsgDeleteBuyerIdsResponse, error)
	CreateBuyers(ctx context.Context, in *MsgCreateBuyers, opts ...grpc.CallOption) (*MsgCreateBuyersResponse, error)
	UpdateBuyers(ctx context.Context, in *MsgUpdateBuyers, opts ...grpc.CallOption) (*MsgUpdateBuyersResponse, error)
	DeleteBuyers(ctx context.Context, in *MsgDeleteBuyers, opts ...grpc.CallOption) (*MsgDeleteBuyersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) CreateBuyerIds(ctx context.Context, in *MsgCreateBuyerIds, opts ...grpc.CallOption) (*MsgCreateBuyerIdsResponse, error) {
	out := new(MsgCreateBuyerIdsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/CreateBuyerIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBuyerIds(ctx context.Context, in *MsgUpdateBuyerIds, opts ...grpc.CallOption) (*MsgUpdateBuyerIdsResponse, error) {
	out := new(MsgUpdateBuyerIdsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/UpdateBuyerIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteBuyerIds(ctx context.Context, in *MsgDeleteBuyerIds, opts ...grpc.CallOption) (*MsgDeleteBuyerIdsResponse, error) {
	out := new(MsgDeleteBuyerIdsResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/DeleteBuyerIds", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) CreateBuyers(ctx context.Context, in *MsgCreateBuyers, opts ...grpc.CallOption) (*MsgCreateBuyersResponse, error) {
	out := new(MsgCreateBuyersResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/CreateBuyers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) UpdateBuyers(ctx context.Context, in *MsgUpdateBuyers, opts ...grpc.CallOption) (*MsgUpdateBuyersResponse, error) {
	out := new(MsgUpdateBuyersResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/UpdateBuyers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) DeleteBuyers(ctx context.Context, in *MsgDeleteBuyers, opts ...grpc.CallOption) (*MsgDeleteBuyersResponse, error) {
	out := new(MsgDeleteBuyersResponse)
	err := c.cc.Invoke(ctx, "/crowlabs.gamma.whitelist.Msg/DeleteBuyers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	CreateBuyerIds(context.Context, *MsgCreateBuyerIds) (*MsgCreateBuyerIdsResponse, error)
	UpdateBuyerIds(context.Context, *MsgUpdateBuyerIds) (*MsgUpdateBuyerIdsResponse, error)
	DeleteBuyerIds(context.Context, *MsgDeleteBuyerIds) (*MsgDeleteBuyerIdsResponse, error)
	CreateBuyers(context.Context, *MsgCreateBuyers) (*MsgCreateBuyersResponse, error)
	UpdateBuyers(context.Context, *MsgUpdateBuyers) (*MsgUpdateBuyersResponse, error)
	DeleteBuyers(context.Context, *MsgDeleteBuyers) (*MsgDeleteBuyersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) CreateBuyerIds(ctx context.Context, req *MsgCreateBuyerIds) (*MsgCreateBuyerIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuyerIds not implemented")
}
func (*UnimplementedMsgServer) UpdateBuyerIds(ctx context.Context, req *MsgUpdateBuyerIds) (*MsgUpdateBuyerIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBuyerIds not implemented")
}
func (*UnimplementedMsgServer) DeleteBuyerIds(ctx context.Context, req *MsgDeleteBuyerIds) (*MsgDeleteBuyerIdsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBuyerIds not implemented")
}
func (*UnimplementedMsgServer) CreateBuyers(ctx context.Context, req *MsgCreateBuyers) (*MsgCreateBuyersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBuyers not implemented")
}
func (*UnimplementedMsgServer) UpdateBuyers(ctx context.Context, req *MsgUpdateBuyers) (*MsgUpdateBuyersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateBuyers not implemented")
}
func (*UnimplementedMsgServer) DeleteBuyers(ctx context.Context, req *MsgDeleteBuyers) (*MsgDeleteBuyersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBuyers not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_CreateBuyerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBuyerIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBuyerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/CreateBuyerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBuyerIds(ctx, req.(*MsgCreateBuyerIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBuyerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBuyerIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBuyerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/UpdateBuyerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBuyerIds(ctx, req.(*MsgUpdateBuyerIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteBuyerIds_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteBuyerIds)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteBuyerIds(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/DeleteBuyerIds",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteBuyerIds(ctx, req.(*MsgDeleteBuyerIds))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_CreateBuyers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgCreateBuyers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).CreateBuyers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/CreateBuyers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).CreateBuyers(ctx, req.(*MsgCreateBuyers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_UpdateBuyers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateBuyers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateBuyers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/UpdateBuyers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateBuyers(ctx, req.(*MsgUpdateBuyers))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_DeleteBuyers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgDeleteBuyers)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).DeleteBuyers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/crowlabs.gamma.whitelist.Msg/DeleteBuyers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).DeleteBuyers(ctx, req.(*MsgDeleteBuyers))
	}
	return interceptor(ctx, in, info, handler)
}

var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "crowlabs.gamma.whitelist.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBuyerIds",
			Handler:    _Msg_CreateBuyerIds_Handler,
		},
		{
			MethodName: "UpdateBuyerIds",
			Handler:    _Msg_UpdateBuyerIds_Handler,
		},
		{
			MethodName: "DeleteBuyerIds",
			Handler:    _Msg_DeleteBuyerIds_Handler,
		},
		{
			MethodName: "CreateBuyers",
			Handler:    _Msg_CreateBuyers_Handler,
		},
		{
			MethodName: "UpdateBuyers",
			Handler:    _Msg_UpdateBuyers_Handler,
		},
		{
			MethodName: "DeleteBuyers",
			Handler:    _Msg_DeleteBuyers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "whitelist/tx.proto",
}

func (m *MsgCreateBuyerIds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBuyerIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBuyerIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccAddr) > 0 {
		i -= len(m.AccAddr)
		copy(dAtA[i:], m.AccAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AccAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBuyerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBuyerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBuyerIdsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBuyerIds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBuyerIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBuyerIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.AccAddr) > 0 {
		i -= len(m.AccAddr)
		copy(dAtA[i:], m.AccAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AccAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBuyerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBuyerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBuyerIdsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBuyerIds) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBuyerIds) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBuyerIds) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.AccAddr) > 0 {
		i -= len(m.AccAddr)
		copy(dAtA[i:], m.AccAddr)
		i = encodeVarintTx(dAtA, i, uint64(len(m.AccAddr)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBuyerIdsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBuyerIdsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBuyerIdsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgCreateBuyers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBuyers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBuyers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Buyer != nil {
		{
			size, err := m.Buyer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgCreateBuyersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgCreateBuyersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgCreateBuyersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBuyers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBuyers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBuyers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Buyer != nil {
		{
			size, err := m.Buyer.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintTx(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateBuyersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateBuyersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateBuyersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBuyers) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBuyers) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBuyers) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BuyerId) > 0 {
		i -= len(m.BuyerId)
		copy(dAtA[i:], m.BuyerId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BuyerId)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.Creator) > 0 {
		i -= len(m.Creator)
		copy(dAtA[i:], m.Creator)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Creator)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgDeleteBuyersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgDeleteBuyersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgDeleteBuyersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgCreateBuyerIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AccAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateBuyerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateBuyerIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AccAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateBuyerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteBuyerIds) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.AccAddr)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteBuyerIdsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgCreateBuyers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Buyer != nil {
		l = m.Buyer.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgCreateBuyersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgUpdateBuyers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.Buyer != nil {
		l = m.Buyer.Size()
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgUpdateBuyersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgDeleteBuyers) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Creator)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BuyerId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgDeleteBuyersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgCreateBuyerIds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBuyerIds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBuyerIds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBuyerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBuyerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBuyerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBuyerIds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBuyerIds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBuyerIds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBuyerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBuyerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBuyerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBuyerIds) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBuyerIds: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBuyerIds: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field AccAddr", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.AccAddr = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBuyerIdsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBuyerIdsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBuyerIdsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBuyers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBuyers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBuyers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buyer == nil {
				m.Buyer = &Buyer{}
			}
			if err := m.Buyer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgCreateBuyersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgCreateBuyersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgCreateBuyersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBuyers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBuyers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBuyers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Buyer", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Buyer == nil {
				m.Buyer = &Buyer{}
			}
			if err := m.Buyer.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateBuyersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateBuyersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateBuyersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBuyers) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBuyers: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBuyers: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Creator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Creator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BuyerId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BuyerId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgDeleteBuyersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgDeleteBuyersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgDeleteBuyersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
